name: kitawi_example
description: An absolute bare-bones web app with kitawi library.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  kitawi:
    path: ../

dev_dependencies:
  build_runner: ^2.4.8
  build_web_compilers: ^4.0.9
  lints: ^3.0.0
