name: example
description: An absolute bare-bones web app.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
publish_to: none
environment:
  sdk: ^3.5.0-180.3.beta

# Add regular dependencies here.
dependencies:
  kitawi:
    path: ../

dev_dependencies:
  build_runner: ^2.4.8
  build_web_compilers: ^4.0.9
  lints: ^4.0.0
