name: kitawi
description: Kitawi is a UI library for Dart web apps.
version: 0.0.9
repository: https://github.com/bryanbill/kitawi

executables:
  kitawi: kitawi

environment:
  sdk: ">=2.14.0 <4.0.0"

dependencies:
  args: ^2.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
