name: kitawi
description: Kitawi is a web UI library based on Flutter's widgets.
version: 0.1.1
repository: https://github.com/bryanbill/kitawi

environment:
  sdk: ^3.5.0-180.3.beta

dependencies:
  web: ^0.5.1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
