name: kitawi
description: Kitawi is a SSR UI Library.
version: 0.1.0
repository: https://github.com/bryanbill/kitawi

executables:
  kitawi: kitawi

environment:
  sdk: ">=2.14.0 <4.0.0"

# dependencies:

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
dependencies:
  grinder: ^0.9.4
