name: kitawi
description: Kitawi is a Dart web library for building web user interfaces. It's highly customizable and can be used with any Dart package that can run on the web.
version: 0.2.1
repository: https://github.com/bryanbill/kitawi

environment:
  sdk: ^3.7.0

executables:
  kitawi: kitawi

dependencies:
  web: ^1.1.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
