name: kitawi
description: A dart web library.
version: 0.1.1
repository: https://github.com/bryanbill/kitawi

environment:
  sdk: ^3.4.3

executables:
  kitawi:

dependencies:
  web: ^1.0.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
