name: kitawi
description: Kitawi is a web UI library based on Flutter's widgets.
version: 0.0.5
repository: https://github.com/bryanbill/kitawi

executables:
  kitawi: kitawi

environment:
  sdk: ">=2.14.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  args: ^2.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  
