name: kitawi
description: Kitawi is a Dart web library for building web user interfaces. It's highly customizable and can be used with any Dart package that can run on the web.
version: 0.1.6
repository: https://github.com/bryanbill/kitawi

environment:
  sdk: ^3.4.3

executables:
  kitawi:

dependencies:
  web: ^1.0.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
