name: Kitawi CI

on:
  push:
    branches: ["main"]

jobs:
  publishing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603

      - name: Install dependencies
        run: dart pub get

      - name: Format code
        run: dart format .

      - name: Analyze project source
        run: dart analyze

      - name: Run JS tests on Chrome
        run: |
          find test/ -name "*.dart" | xargs -n 1 dart test -p chrome --compiler dart2js

      - name: Run WASM tests on Chrome
        run: |
          find test/ -name "*.dart" | xargs -n 1 dart test -p chrome --compiler dart2wasm

      - name: "Publish package"
        uses: k-paxian/dart-package-publisher@master
        with:
          accessToken: ${{ secrets.OAUTH_ACCESS_TOKEN }}
          refreshToken: ${{ secrets.OAUTH_REFRESH_TOKEN }}
